### ISSUE TITLE
bug(global): Copy buttons not working 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#283] opened 2024-07-17 23:03 UTC
**Issue:**
After refreshing the webpage if you log back in and try to copy your did by just normally left clicking it, it doesnt seem to work, when you paste it nothing is there.

Note that this only happens when you run `npm run build` followed by `npm run preview`.

When you click the copy button an error is given in console (Error shown below).

**Steps to reproduce:**
- Refresh your webpage
- Log into your account again
- Navigate to Friends or Profiles and try to copy your did:key by just left clicking like normal using the context menu by right clicking still works fine (its also good to have something like a url copied to your clipboard so you can be sure after clicking the button its copying the did)

**Screemnshot:**
![image](https://github.com/user-attachments/assets/c66261f4-d34d-48b4-b919-708e7b2d1b54)

**Comment by ashneverdawn** [comment] 2024-07-18 13:36
@tooshel showed me this and I was able to reproduce it too. He noticed it only happens when using the ip address, when using localhost this issue doesn't happen. After some searching, I found the apparent reason for this:
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined
```
This requires a secure origin — either HTTPS or localhost (or disabled by running Chrome with a flag)
```

**Comment by ashneverdawn** [comment] 2024-07-18 13:39
Of note, while this is generally a non issue at the moment since we can just use localhost, if we started testing on real mobile devices we'd have to use the ip in that case.

**Comment by tooshel** [comment] 2024-07-18 15:46
@phillsatellite Probably nothing we can do about this for now. I think Hugo makes a good point that when we are testing on mobile it's likely we are going to test via IP address but we'll have to figure out self signed local certs or something like that. But that's a different problem and if we want someone to fix that we should be specific and just make this benefit a side note. Should probably close this for now.

**Closed as completed** 2024-07-18 15:54 UTC
Labels: bug, 🥇 High Priority
